name: cml_umap_example
channels:
  - conda-forge
  - defaults
dependencies:
  - ipympl=0.4.1
  - ipywidgets=7.5.1
  - jupyterlab=1.2.6
  - netcdf4=1.5.3
  - numpy=1.18.1
  - pandas=1.0.1
  - python=3.8.1
  - pytz=2019.3
  - scikit-learn=0.22.1
  - seaborn=0.10.0
  - statsmodels=0.11.0
  - tqdm=4.42.1
  - traitlets=4.3.3
  - umap-learn=0.3.10
  - widgetsnbextension=3.5.1
  - xarray=0.15.0
